### ISSUE TITLE
希望支持星穹铁道版区

### ISSUE THREAD

**Issue by xANoyU** [FailDragon-Plus/auto_mys#1]
rt, 还有module_id可以填多个版区吗?

**Comment by Ljzd-PRO** [comment]
目前不行，有空我试试

**Comment by xANoyU** [comment]
> 目前不行，有空我试试

start.py > 251行 添加一行 `'5': '52'` 就可以跑星穹铁道了hh

**Comment by Ljzd-PRO** [comment]
好的谢谢

**Comment by Ljzd-PRO** [comment]
现在多版区ID也可以了，应该没什么问题
https://github.com/Ljzd-PRO/auto_mys/releases/tag/v1.3.0
