### ISSUE TITLE
可以更新一下吗

### ISSUE THREAD

**Issue by xANoyU** [FailDragon-Plus/auto_mys#4]
只要修改`start.py`中第50行的salt值为`9nQiU3AV0rJSIBWgdynfoGMGKaklfbM7`（抄来的）就可以运行大部分功能了。
只是有个地方搞不懂，频道等级任务的点赞数增加了，但是米游币任务里的点赞数不增加，球球可以修复一下>_<

**Comment by Ljzd-PRO** [comment]
嗯，另外URL也变化了，所以很多地方不行

**Comment by Ljzd-PRO** [comment]
有太多地方要改了，再加上这个是之前做的，问题比较多，现在归档了。可以尝试新的项目

米游币任务、游戏签到、商品兑换都有。

https://github.com/Ljzd-PRO/nonebot-plugin-mystool
